# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nsainton <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/12/08 07:00:14 by nsainton          #+#    #+#              #
#    Updated: 2022/12/10 01:10:17 by nsainton         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

git:
	git add --all
	git commit
	git push origin dev

merge:
	git checkout main
	git pull
	git merge dev
	git push origin main
	git checkout dev


